spring:
  application:
    name: scada.mobile.backend


# Configuration для PrintSrvClient
printsrv:
  ip: 127.0.0.1
  port: 10101
  pool:
    size: 5

logging:
  level:
    dev.savushkin.scada.mobile.backend.client: DEBUG
